// `dotnet test` under Microsoft.Testing.Platform. The shape is:
//
//   failed Namespace.Class.Method (11ms)
//     Assert.Equal() Failure: Values differ
//     Expected: Transient
//     Actual:   Singleton
//     from /path/to/Tests.dll (net10.0|arm64)
//     ...the same message again, indented differently...
//       at Namespace.Class.Method() in /path/Tests.cs:395
//       at System.Reflection.MethodBaseInvoker...        <- framework noise
//
// The message is printed twice, once plainly and once re-indented under `from`.
// Only the first copy is kept, and only the frame in the user's own code is used
// for the location.
const FAILED_RE = /^failed[ \t]+(\S+)[ \t]+\((\d+(?:\.\d+)?)[ \t]*m?s\)[ \t]*$/;
const AT_RE = /^[ \t]*at[ \t]+(.+?)[ \t]+in[ \t]+(.+?):(?:line[ \t]+)?(\d+)[ \t]*$/;
const FRAMEWORK = /^(?:System\.|Microsoft\.|Xunit\.|NUnit\.|InternalAutoGenerated)/;
const MAX_MESSAGE_LINES = 4;

/** "Namespace.Class.Method" reads better as "Class.Method". */
function shortName(fq) {
  const parts = fq.split(".");
  return parts.length > 2 ? parts.slice(-2).join(".") : fq;
}

export default {
  name: "dotnet test",
  detect: (s) => FAILED_RE.test(s.split("\n").find((l) => FAILED_RE.test(l)) ?? "") &&
    /^[ \t]*Test run summary:/m.test(s),

  extract(s) {
    const lines = s.split("\n");
    const failures = [];

    for (let i = 0; i < lines.length; i++) {
      const head = lines[i].match(FAILED_RE);
      if (!head) continue;

      const msg = [];
      let file, line, repeated = false;
      for (let j = i + 1; j < lines.length && !FAILED_RE.test(lines[j]); j++) {
        const at = lines[j].match(AT_RE);
        if (at) {
          // the first frame in the user's own code wins; the rest is the runner
          if (!file && !FRAMEWORK.test(at[1])) { file = at[2]; line = +at[3]; }
          continue;
        }
        // `from <dll>` closes the first copy of the message. Everything after it is
        // the same text re-indented, so stop collecting - but keep scanning, because
        // the stack frames that carry the location come after the repeat.
        if (/^[ \t]*from[ \t]+\S+\.dll/.test(lines[j])) { repeated = true; continue; }
        const t = lines[j].trim();
        if (repeated || !t || msg.length >= MAX_MESSAGE_LINES) continue;
        if (/^Standard output:/.test(t) || /^Test run summary:/.test(t) || /^Exit code:/.test(t)) break;
        msg.push(t);
      }

      failures.push({
        file, line,
        title: shortName(head[1]),
        message: msg.join("\n"),
      });
    }

    if (!failures.length) return null;

    // "total: 80 / failed: 3 / succeeded: 77" -> "3 failed, 77 passed (80)"
    const num = (k) => {
      const m = s.match(new RegExp(String.raw`^[ \t]*${k}:[ \t]*(\d+)[ \t]*$`, "m"));
      return m ? +m[1] : null;
    };
    const [total, failed, ok, skipped] = ["total", "failed", "succeeded", "skipped"].map(num);
    const bits = [];
    if (failed) bits.push(`${failed} failed`);
    if (ok) bits.push(`${ok} passed`);
    if (skipped) bits.push(`${skipped} skipped`);
    const summary = bits.length ? `${bits.join(", ")}${total ? ` (${total})` : ""}` : undefined;

    return { tool: "dotnet test", summary, failures };
  },
};
