// `dotnet test` under Microsoft.Testing.Platform. The shape is:
//
//   failed Namespace.Class.Method (11ms)
//     Assert.Equal() Failure: Values differ
//     Expected: Transient
//     Actual:   Singleton
//     from /path/to/Tests.dll (net10.0|arm64)
//     ...the same message again, indented differently...
//       at Namespace.Class.Method() in /path/Tests.cs:395
//       at System.Reflection.MethodBaseInvoker...        <- framework noise
//
// The message is printed twice, once plainly and once re-indented under `from`.
// Only the first copy is kept, and only the frame in the user's own code is used
// for the location.
//
// VSTest uses `Failed Namespace.Class.Method [2 ms]`, followed by labelled Error
// Message and Stack Trace blocks. It may also print xUnit's prefixed copy first; the
// labelled result is the stable cross-framework surface and is the one parsed below.
import { SOURCE_RANGE } from "../ownership.js";

const MTP_FAILED_RE = /^failed[^\S\n]+(\S+)[^\S\n]+\((\d+(?:\.\d+)?)[^\S\n]*m?s\)[^\S\n]*$/;
const VSTEST_FAILED_RE = /^[^\S\n]+Failed[^\S\n]+(.+?)[^\S\n]+\[(?:<[^\S\n]+)?\d+(?:\.\d+)?[^\S\n]*(?:ms|s)\][^\S\n]*$/;
const VSTEST_RESULT_RE = /^[^\S\n]+(?:Failed|Passed|Skipped)[^\S\n]+.+?[^\S\n]+\[(?:<[^\S\n]+)?\d+(?:\.\d+)?[^\S\n]*(?:ms|s)\][^\S\n]*$/;
const VSTEST_END_RE = /^(?:Test Run Failed\.|Failed![^\n]*\bFailed:[^\S\n]*\d+)/m;
const AT_RE = /^[^\S\n]*at[^\S\n]+(.+?)[^\S\n]+in[^\S\n]+(.+?):(?:line[^\S\n]+)?(\d+)[^\S\n]*$/;
const FRAMEWORK = /^(?:System\.|Microsoft\.|Xunit\.|NUnit\.|InternalAutoGenerated)/;
const MAX_MESSAGE_LINES = 4;

/** "Namespace.Class.Method" reads better as "Class.Method". */
function shortName(fq) {
  const parts = fq.split(".");
  return parts.length > 2 ? parts.slice(-2).join(".") : fq;
}

function rangedFailure(failure, start, end) {
  Object.defineProperty(failure, SOURCE_RANGE, { value: { start, end }, enumerable: false });
  return failure;
}

function summaryNumber(text, key) {
  if (key === "total") {
    const tests = text.match(/^Total tests:[^\S\n]*(\d+)[^\S\n]*$/im);
    if (tests) return +tests[1];
  }
  const standalone = text.match(new RegExp(String.raw`^[^\S\n]*${key}:[^\S\n]*(\d+)[^\S\n]*$`, "im"));
  if (standalone) return +standalone[1];
  const compact = text.match(new RegExp(String.raw`\b${key}:[^\S\n]*(\d+)`, "i"));
  return compact ? +compact[1] : null;
}

function summary(text) {
  const [total, failed, ok, skipped] = ["total", "failed", "passed", "skipped"]
    .map((key) => summaryNumber(text, key));
  const bits = [];
  if (failed) bits.push(`${failed} failed`);
  if (ok) bits.push(`${ok} passed`);
  if (skipped) bits.push(`${skipped} skipped`);
  return bits.length ? `${bits.join(", ")}${total ? ` (${total})` : ""}` : undefined;
}

function vstest(text) {
  if (!VSTEST_END_RE.test(text)) return null;
  const lines = text.split("\n");
  const failures = [];
  for (let i = 0; i < lines.length; i++) {
    const head = lines[i].match(VSTEST_FAILED_RE);
    if (!head) continue;
    let end = i + 1;
    while (end < lines.length && !VSTEST_RESULT_RE.test(lines[end]) &&
      !/^(?:Test Run (?:Failed|Successful)\.|Total tests:|Failed![^\n]*\bFailed:)/.test(lines[end])) end++;

    const message = [];
    let file, line, collecting = false;
    for (let j = i + 1; j < end; j++) {
      const frame = lines[j].match(AT_RE);
      if (frame) {
        if (!file && !FRAMEWORK.test(frame[1])) { file = frame[2]; line = +frame[3]; }
        continue;
      }
      const value = lines[j].trim();
      if (value === "Error Message:") { collecting = true; continue; }
      if (value === "Stack Trace:") { collecting = false; continue; }
      if (collecting && value && message.length < MAX_MESSAGE_LINES) message.push(value);
    }
    failures.push(rangedFailure({
      file, line, title: shortName(head[1]), subject: shortName(head[1]), severity: "error",
      message: message.join("\n") || "test failed",
    }, i, end));
    i = end - 1;
  }
  const runs = text.match(new RegExp(VSTEST_END_RE.source, "gm"))?.length ?? 0;
  return failures.length ? { failures, summary: runs === 1 ? summary(text) : undefined } : null;
}

export default {
  name: "dotnet test",
  category: "test",
  commands: ["dotnet"],
  detect: (s) => (MTP_FAILED_RE.test(s.split("\n").find((l) => MTP_FAILED_RE.test(l)) ?? "") &&
    /^[^\S\n]*Test run summary:/m.test(s)) || !!vstest(s),

  extract(s) {
    const vs = vstest(s);
    const lines = s.split("\n");
    const failures = [];

    for (let i = 0; i < lines.length; i++) {
      const head = lines[i].match(MTP_FAILED_RE);
      if (!head) continue;

      const msg = [];
      let file, line, repeated = false;
      for (let j = i + 1; j < lines.length && !MTP_FAILED_RE.test(lines[j]); j++) {
        const at = lines[j].match(AT_RE);
        if (at) {
          // the first frame in the user's own code wins; the rest is the runner
          if (!file && !FRAMEWORK.test(at[1])) { file = at[2]; line = +at[3]; }
          continue;
        }
        // `from <dll>` closes the first copy of the message. Everything after it is
        // the same text re-indented, so stop collecting - but keep scanning, because
        // the stack frames that carry the location come after the repeat.
        if (/^[^\S\n]*from[^\S\n]+\S+\.dll/.test(lines[j])) { repeated = true; continue; }
        const t = lines[j].trim();
        if (repeated || !t || msg.length >= MAX_MESSAGE_LINES) continue;
        if (/^Standard output:/.test(t) || /^Test run summary:/.test(t) || /^Exit code:/.test(t)) break;
        msg.push(t);
      }

      failures.push({
        file, line,
        title: shortName(head[1]), subject: shortName(head[1]), severity: "error",
        message: msg.join("\n"),
      });
    }

    if (!failures.length) {
      return vs ? { tool: "dotnet test", summary: vs.summary, failures: vs.failures } : null;
    }
    // CI may concatenate retries from different .NET test runners. Both encodings are
    // real runs; keep both failure sets and do not present either run's tally as if it
    // described their combination.
    if (vs) return { tool: "dotnet test", failures: [...vs.failures, ...failures] };

    // "total: 80 / failed: 3 / succeeded: 77" -> "3 failed, 77 passed (80)"
    const num = (k) => {
      const m = s.match(new RegExp(String.raw`^[^\S\n]*${k}:[^\S\n]*(\d+)[^\S\n]*$`, "m"));
      return m ? +m[1] : null;
    };
    const [total, failed, ok, skipped] = ["total", "failed", "succeeded", "skipped"].map(num);
    const bits = [];
    if (failed) bits.push(`${failed} failed`);
    if (ok) bits.push(`${ok} passed`);
    if (skipped) bits.push(`${skipped} skipped`);
    const summary = bits.length ? `${bits.join(", ")}${total ? ` (${total})` : ""}` : undefined;

    return { tool: "dotnet test", summary, failures };
  },
};
